version: "3.0"
services: 
    wpg-food-list-db:
        image: mysql:5.6
        container_name: wpg-food-list-db
        ports:
            - "3318:3306"
        expose: 
            - "3306"
        environment: 
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: wpg-food-list